service: garden-aid-web-bff
provider:
    name: aws
    runtime: nodejs4.3
    stage: dev
    region: ap-southeast-2
    iamRoleStatements:
       -  Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:ap-southeast-2:*:*"
package:
    include:
      - node_modules
      - src
    exclude:
      - coverage
      - tests
      - .editorconfig
      - .eslintignore
      - .gitignore
      - .synk
      - .travis.yml
      - .create-secrets.js
      - deploy.sh
      - LICENSE
      - package.json
      - README.md

functions:
    graphQl:
        handler: index.graphql
        memory: 512
        timeout: 3
        events:
            - http:
                path: graphql
                method: post
                cors: true
                authorizer:
                  name: authorize
                  resultTtlInSeconds: 30
    authorize:
        handler: index.authorize
        memory: 512
        timeout: 3
